### ISSUE TITLE
Can we make the names prettier please?

### ISSUE THREAD

**Issue by tralph3** [libretro/libretro-database#1029]
There are many games that have their names badly wirtten. I'm not a guy who downloads a huge chunk of roms to then play none of them, I download games as I want them, and even in my comparatevely small collection, I already found some issues with the names. As the name of a game in a playlist has to be exactly the same for it to be linked to its database entry (for some stupid reason) I have no choice but to name my games like that, and it's bad. For example, The Legend of Zelda, the original, has the "The" at the end, like so: "Legend of Zelda, The" Why? Really why? Parasite Eve II, has its number written as a "2" instead of "II". This would be a non issue if there was another way to link games rather than by its name.

**Comment by RobLoach** [comment]
> "Legend of Zelda, The" Why? Really why?

We use [No-Intro](https://datomatic.no-intro.org/)'s [No-Intro Naming Convention](https://datomatic.no-intro.org/stuff/The%20Official%20No-Intro%20Convention%20(20071030).pdf). If there are issues you'd like to make in No-Intro, they are very responsive in their forum:
https://datomatic.no-intro.org/?page=forum

> Parasite Eve II, has its number written as a "2" instead of "II".

Up until recently, this was using [PSXDataCenter](http://psxdatacenter.com). We're in the process over moving over to [Redump](http://redump.org/) for it, which has the II instead of 2.

**Comment by tralph3** [comment]
Fine, I can understand why they are namde as they are, doesn't mean there's not an issue here. Game shouldn't be linked to their database entry by their name, or at the very least users should be able to manually relink games to databse entries.

**Comment by RobLoach** [comment]
Would be great to be able to rename playlist entries, and keep the thumbnail/description in there. There's an issue over at https://github.com/libretro/RetroArch/issues/10093 to tackle that.
