### ISSUE TITLE
Regressions - please read

### ISSUE THREAD

**Issue by twinaphex** [libretro/libretro-database#1069]
I see some stuff has changed with the PS1 database which I think was not intentional.

1. 'Origin' now no longer refers to the 'origin' that the game comes from. Instead - it now seems to assume just the 'region' in which the game released. This is wrong.
2.  'Publisher' is now gone.

![image](https://user-images.githubusercontent.com/1075274/84034917-47550280-a99b-11ea-994a-e8467212a652.png)

You can check out what is broken by checking the following cursors - the following no longer work:

list-all-ps1-games-from-publisher-eidos.dbc is broken
list_all_ps1_games_with_uk_origin.dbc is broken
test.dbc

**Comment by twinaphex** [comment]
If changing the definition of 'Origin' was a deliberate choice, we might have to bring back the old 'Origin' under  a new name 'Country of Origin' or something. I could hook up the code if needed on the RetroArch side.

First I need to know from some of you though what has happened here, and in the future, please check these changes with me first before you push this through. Always check out the cursor files too to see if there is any regressions you made to the databases. We should probably make more cursor files as it's a good regression testing tool.

**Comment by RobLoach** [comment]
1. Origin
  Renamed what was `origin` over to `region`.... This was a misunderstanding of what the property was used for.

2. Publisher
  PSXDatabase provided the `publisher` information, but was removed since there was a lot of inconsistency in the data it provided. I've updated the PSXDatabase data with the `publisher` in there. Tested with the new RDBs and it's up and running....

![Screenshot at 2020-06-08 12-40-28](https://user-images.githubusercontent.com/25086/84057217-5d57c880-a985-11ea-8dc3-a82f6d56eb86.png)

Thanks a lot!
