### ISSUE TITLE
Add Redump Sega CD - Mega CD to the database

### ISSUE THREAD

**Issue by markwkidd** [libretro/libretro-database#232]
There is a Redump-verified Sega CD - Mega CD collection out there in circulation. Would it make sense to add this to the database?

Direct link to Redump's DAT: http://redump.org/datfile/scd/

**Comment by markwkidd** [comment]
Inspired in part by an issue here: https://github.com/libretro/RetroArch/issues/3353

**Comment by shinra358** [comment]
Do I put that dat file somewhere or do I just wait for integration?

**Comment by markwkidd** [comment]
Right now you have to wait for integration, although this issue should be where you can check back to see if it will be added. (With a Redump DAT and a set of ROMs in circulation I think there is a good chance)

In the meantime we need to figure out why your custom playlist is crashing back in your original ticket. That should have been the temporary solution for this.

**Comment by RobLoach** [comment]
The Redump DAT is an XML, so we'll have to adapt it over to a libretro DAT. I've put together a script for Sega Saturn at https://github.com/RobLoach/libretro-database-sega-saturn . Could use that as a base to create a Mega CD one.

Since Genesis Plus GX supports .cue, we should strip all the other rom entries, and just list the CUE files.

**Comment by markwkidd** [comment]
Thank you @RobLoach for getting the DAT merged into the database -- it seems that most of my Issues and Pulls wind up on your desk lately!

I'll close this ticket.
