### ISSUE TITLE
Add LICENSE.md

### ISSUE THREAD

**Issue by RobLoach** [libretro/libretro-database#461]
What license does this fall under?

- GPLv3
- MIT

Thoughts?

**Comment by markwkidd** [comment]
I have no particular status, but I would like to speak as an advocate of a certain philosophy.

There are and have been many attempts to create meta-databases of ROMs ever since the beginning of the Internet. Unfortunately there has not always been continuity between these efforts.

This meta-database may be the best one ever to date. Please consider licensing it under the most permissible license possible for the sake of other present and future efforts to carry the torch. The easier it is to adapt, the better the chance that this database will continue to serve in the long term.
