### ISSUE TITLE
Group Multiple Disks in the menu

### ISSUE THREAD

**Issue by i30817** [libretro/libretro-database#476]
Like obviously, no one is a fan of the .cmd files, even if they sometimes are useful (to reorder the default 'order' for a clean boot i've found on pc-98 emulation).

I believe usability of the frontend could be very enhanced (without user hacks like 'use .pbp') if the database had some 'group scan', that would only be added once all members of the group were recognized. Obviously this is quite different from 'iterate over all files, 'yes/no' but i truly believe it's a good idea.

It can also be done, *after* scanning, as a post-process check. Iterate over all added games, find those that are part of a set, replace their entries by a single one that allows disk change in the GUI.

Both redump, and TOSEC use the construct "(Disk X of Y)"¹ or "(Disk X)" (of a max on the database) of the same name on their index files to mark groups. This can easily be done with few false positives (none?), even without actual modification of the dat files, just by checking for a complete set of associated game names on the dat for the associated crcs of the files added (easily done with sorting).

¹ even for diskettes and similar.

**Comment by RobLoach** [comment]
So when the menu finds (Disk X), replace all entries with a full group? You would enter the group, and then select the disk #?

Interesting idea. Unsure how to implement it in the menu.

**Comment by i30817** [comment]
Yes that's it. There are a few multidisk games whose disks had different names and wouldn't be picked up (this doesn't matter because they'd still show) but that's because they probably shouldn't eg: VR Missions in metal  gear solid, Langrisser IV nad Langrisser V in the Langrisser compilation etc.

**Comment by i30817** [comment]
BTW, it's (unfortunately) probably safer to use the actual filename instead of the mapping (crc32->game name) in the DAT because some of the sets have index files with the same crc (i'm looking at you dreamcast TOSEC and trurip).

**Comment by i30817** [comment]
> So when the menu finds (Disk X), replace all entries with a full group? You would enter the group, and then select the disk #?

There are some nuances here for the Japanese computers. PC-98 and X68000 expected to get two floppies at the same time during booting (most times).

**Comment by RobLoach** [comment]
Yeah, seems rather complicated. Don't want to get into weird use cases. And the menu is difficult to work with already.

**Comment by RobLoach** [comment]
This would be a lot of work, and I'm not sure of its implementation. Touches on the RA menu, and the individual cores.

**Comment by fr500** [comment]
Well, first thing that would need to be supported is the subsystem API via the regular load content menu
https://github.com/libretro/RetroArch/pull/5161

It's still not working because... well I'm lazy and a bit of lack of help I guess, I still haven't figured how to trigger the load content menu.

Once that is done, it could be used for:
- Loading MAME roms!, yeah, it could give us a list of MAME media types (cart1, cart2, flop1, flop2, etc) and allow us to load them via the menu
- Loading different games in each emulated GB in TGB dual
- Loading SGB / Sufami / BSX
- Loading 4 different games in the multi mGBA core, link them if I ever figure how to link them
- Load 2 floppies on x68K

After manual loading is implemented I think we need to improve the playlist format (or even better, replace it with json).

Then, and only then a playlist could store all the information required to load all these multiple media games.

**Comment by RobLoach** [comment]
Le'ts continue this discussion over at https://github.com/libretro/RetroArch/pull/5161 . This goes well beyond libretro-database.
