### ISSUE TITLE
Gameboy and Gameboy Color

### ISSUE THREAD

**Issue by Kivutar** [libretro/libretro-database#537]
@RobLoach 

Reported on the forums:

https://forums.libretro.com/t/lakka-2-1-rc5-released/12720/10

**Comment by RobLoach** [comment]
GoodTools GoodGB was broght in, and it unfortunately doesn't split GB from GBC. We have two options:

1. Remove GoodGB.
2. Manually split GoodGB into GB and GBC (lot of maintenance work)

For now, we may be best to just remove it and then possibly add it back if we get it to split.

**Comment by RobLoach** [comment]
Renamed GoodGBx so that it doesn't pick it up into Game Boy Color.

**Comment by Mr-Jake** [comment]
@ RobLoach 
An issue was posted in the forum link that a No-Intro set after scanning was being listed in the playlist using the GoodGB naming convention. If a ROM has the same CRC in both GoodTools and No-Intro, which naming convention is used? Can you specify to use only No-Intro?

**Comment by RobLoach** [comment]
@Mr-Jake We simply removed GoodTools' GoodGBx. Update your databases and it should be good.

To do it "right", we would need to...

1. Split GoodGBx to Game Boy and Game Boy Color
2. Rename the entries manually to No-Intro naming scheme
3. Maintain them so that updates from GoodTools are brought in

Not really worth the effort, in my opinion. So we just removed GoodGBx for now.

**Comment by Zerauskire** [comment]
Well when and if you do get around to adding back in GoodGBx, I personally don't mind GB and GBC being combined. My only concern was the different naming conventions in the same category. It just looked odd. 

As a matter of fact I wouldn't mind the GoodSets being used as a standard for all roms only because then more would be detected than with No-Intro. While I do love the goal of perfection and purity that No-Intro strives for in their dumps, not everyone has or cares to have the perfect dump of every game. No-Intro has a cleaner look to it though. The naming convention for GoodSets almost requires a decoder ring.

Maybe you could just work on something that uses the raw GoodSets dat files and just parses/replaces the data client side as it displays. So have it look for something like (U) and replaces it with the full text (USA). Then just drop the [!] all together since it just indicates a good dump. Then leave the other flags or replace them too. Honestly that could even solve your current issue. Anyone with No-Intro sets would show up as "(U)[!]" so if you did a swap of the (U) to (USA) and dropped the [!] they would match even though they were being scanned using different .dats.

Just a thought....

**Comment by Zerauskire** [comment]
Ohh and the (v0.1) stuff to (Rev1) etc.. forgot about that. I'm sure i'm probably forgetting more but I think you get the idea..

**Comment by Kivutar** [comment]
It's not really acceptable to have GB and GBC mixed. We're getting bug reports about it.
