### ISSUE TITLE
Tomb Raider openLara

### ISSUE THREAD

**Issue by RobLoach** [libretro/libretro-database#645]
Allow loading the PSX and Sega Saturn data files? Also make sure all levels are listed in the DAT too.

**Comment by i30817** [comment]
Ok, i checked unfinished business psx and t's a clone cd image here, that is:

/media/i30817/backup/Documents/Games/Sony - PlayStation/Tomb Raider 1.5 - Unfinished Business/Tomb Raider 1.5 - Unfinished Business.sub
/media/i30817/backup/Documents/Games/Sony - PlayStation/Tomb Raider 1.5 - Unfinished Business/Tomb Raider 1.5 - Unfinished Business.img
/media/i30817/backup/Documents/Games/Sony - PlayStation/Tomb Raider 1.5 - Unfinished Business/Tomb Raider 1.5 - Unfinished Business.ccd

Which file should i use as signature, the img? And can retroarch load a game from that?


Speaking of loading games, i've been under the assumption that the 'filename' part of the entry doesn't matter for loading hacks (and it might not do for roms which are a single file).

But some roms which aren't a single file, such as for example psx1 hacks where typically one track of the game is changed, or this case here where are three files, how does RA launch the file to the core, just the matching file?

Because that probably causes artifacts for some games (psx games without audio tracks etc). Or is there some wizardry like 'for every file that matches and isn't a recognized rom start file, look for a cue on that dir, or something strange like that?

**Comment by i30817** [comment]
Basically, i'm looking for a idea of 

'if i add a hack from a multi-file format, which file should i add, and if the index file chose isn't different from the original, what then?'
