### ISSUE TITLE
quick question about having to use crc

### ISSUE THREAD

**Issue by grant2258** [libretro/libretro-database#650]
Its not ideal for emulators such as mame and fba because zip compression levels or someone adding a readme.txt in the zip file could put this off. It there a solution to use a by filename only. I can parse all the data for mame2003 and 2003 plus but the crcs will be an issue in this case

**Comment by i30817** [comment]
torrentzip can turn MAME and etc roms into recognizable 'zips' at the cost of mandating a compression level (usually max).

**Comment by grant2258** [comment]
yea  we would need to support split and none merged zip name per mame version would be ideal was just wondering if its possible to do without  a crc is all

**Comment by i30817** [comment]
The only alternative to crc (it isn't really a alternative for various reasons, such as hacks, but RA likes to pretend it is) is serials matching which doesn't exist on arcade games. 

Name matching was shot down from the design from day one (and is actually impossible in some cores, like scummvm).

**Comment by grant2258** [comment]
okies well that make s my idea if making a list a no brainer thanks for clarifying though

**Comment by i30817** [comment]
I'm not really asserting that the scanner today is good enough -  i prefer split sets for instance and those haven't been updated in a while if i'm correct (probably because it's easier to support a game with a single archive) [and the scanner has dumb bugs like this](https://github.com/libretro/RetroArch/issues/6699).

**Comment by i30817** [comment]
I wouldn't mind a filename scan myself, but only if it could be made to work fine with hacks. That is, every hack had the 'filename' of the original rom/cd on the database (i do this on the hacks i enter when appropriate) and the Scanner checks first if the filename given for the iso/rom is on the hacks database and if it is, uses a checksum check to make sure.

But someone would need to fix the scanner in Retroarch to perform that type of two-step validation before this strategy worked.
Otherwise games would simply never match a hack. Funny enough this is *already* happening with serial matching because it's another case of fuzzy match.

**Comment by grant2258** [comment]
well for mame my idea was simple we grab the dat from mame and extract the romnames and description per mame version. Just match this name and show the description when the zipfile matches.

on some systems files will change crc like foppys saving ect. I dont know what a perfect solution would be. In my case im not trying to verify the rom. im just trying to give it a descriptive name based on filename.zip
