### ISSUE TITLE
add all cheats winkawaks to libretro-database

### ISSUE THREAD

**Issue by Eignar17** [libretro/libretro-database#722]
.dat to .cht

[cheats.zip](https://github.com/libretro/libretro-database/files/2471309/cheats.zip)

please @RobLoach

**Comment by RobLoach** [comment]
Looks like these would need to be ported over. Mind creating a git repository for these so that they're easier to browse? Thanks!

**Comment by Eignar17** [comment]
ok

**Comment by Eignar17** [comment]
https://github.com/Eignar17/kawaks-cheats

**Comment by Smoker1** [comment]
Might not work. When I was doing my Cheat Search, I found that all the Addresses were either +/- 1-3 for the FBA Core (Latest).
https://github.com/Smoker1/RetroArch-174-and-above-Cheats

**Comment by Eignar17** [comment]
@Smoker1 diferent roms or emulator is problem :/

**Comment by RobLoach** [comment]
Looks great! If you format them to match the directories of libretro-database, and send a PR, we could merge it in.

**Comment by jakirhossainqqpp1100-cloud** [comment]
Subject: Compatibility Issue with Kawaks Emulator on Android 14/15
Dear Kawaks Team,
I am a long-time user of the Kawaks emulator, and I truly appreciate its classic arcade support. However, I have noticed that on my Android device (running Android 14/15), the 64-bit version of Kawaks is not functioning properly. I kindly request that you update and ensure compatibility with the latest Android versions so that we can continue enjoying the emulator without issues.
Thank you for your time and consideration.
Best regards,
[Jaks Victor]
