### ISSUE TITLE
"NEC - PC Engine SuperGrafx" and "Microsoft - MSX2" typo in no-intro DAT-o-MATIC

### ISSUE THREAD

**Issue by sergiobenrocha2** [libretro/libretro-database#73]
Creating this issue just to reminder that NEC - PC Engine SuperGrafx has a typo in the no-intro dat

http://datomatic.no-intro.org/index.php?page=forum&op=browse&thread=2317

https://en.wikipedia.org/wiki/PC_Engine_SuperGrafx

Please don't mess with these files... you change the name in one file it must be changed in another 6 different places... I fixed that 6 months ago...

**Comment by sergiobenrocha2** [comment]
Microsoft - MSX2 has the same typo

**Comment by RobLoach** [comment]
We should go with what No-Intro provides, and push that change upstream to No-Intro if possible. Their forums might be a good place to start that discussion.

**Comment by sergiobenrocha2** [comment]
I reported it but nobody answers...

**Comment by Kivutar** [comment]
Have you tried reported it on their forums instead of their website? I think you would get a reply.

I got some users wanting to contribute and they were confused about this change we made. It's natural for users to think that no-intro is right (while they are wrong in this case).

So I would also prefer if we stick with what no-intro use and ask them to fix it on their side. I registered on their forums and I'm waiting for the confirmation of my account.

**Comment by lollo78** [comment]
Hi guys, I'm registered on their forum: http://forums.no-intro.org.
I did it some months ago, but I never posted nothing until now.
If I remeber well, it's a long procedure: they manually approve all the new subscriptions after analyzing the motivations of the applicant.
So, if you tell me exatcly what I have to ask, and you give me the authorization to speak for the Libretro Team, I can post quickly a request for you.

I noticed the typo inside SuperGrafx .dat (they write "NEC - Super Grafx" instead of "NEC - PC Engine SuperGrafx"), but I'm not sure about the typo for MSX 2: they write "Microsoft - MSX 2" instead "Microsoft - MSX2? So we ask to remove only the space between MSX and 2, right?

**Comment by Kivutar** [comment]
Looks like their forum are down now.

**Comment by RobLoach** [comment]
I suggest closing this. We roll with what No-Intro gives us.

**Comment by Kivutar** [comment]
I agree with you, but @sergiobenrocha2 doesn't agree

**Comment by RobLoach** [comment]
The entries may be passed through translation in RetroArch. It may be possible to translate to the "correct" spelling in the frontend, while keeping them No-Intro-style internally.

**Comment by sergiobenrocha2** [comment]
No, please don't do that, we'll have to change back stuff from dozen places. I can update these databases this week.

**Comment by Kivutar** [comment]
This change have been the source of a lot of bugs in the past. Some of these bugs are still present, like we still serve two thumbnail packs. We should never have changed it in the first place without upstreaming it first.

Now what is done is done and going back could take a lot of time.

I'm still in favor of going back, because conforming to no-intro makes our resources usable by other projects outside of the libretro scope.

@twinaphex were also in favor of rolling back that change the last time we discussed it on IRC.

So I think you're the only one in the team wanting to keep the right name @sergiobenrocha2

**Comment by sergiobenrocha2** [comment]
Then next month they fix it, and we have to change back again. Good luck.

**Comment by Kivutar** [comment]
Yeah... That's a possibility. I posted on their forums some weeks ago and they did nothing. Why is it so difficult to join these people?

BTW, their forum are down :(

**Comment by sergiobenrocha2** [comment]
I was going to update MSX2 dat, and for my surprise it last update was 2015-08-03. So we really need to move from "MSX2" to "MSX 2" ? I thought this thing was update monthly...

**Comment by RobLoach** [comment]
> I thought this thing was update monthly...

It happens whenever someone updates it.

**Comment by RobLoach** [comment]
Going to close this for now. I see the discussion topics you started up. Let's continue talks there.

**Comment by sergiobenrocha2** [comment]
this? http://datomatic.no-intro.org/index.php?page=forum&op=browse&s=13&thread=2317

**Comment by RobLoach** [comment]
http://datomatic.no-intro.org/index.php?page=forum&op=browse&s=13&thread=2548
http://datomatic.no-intro.org/index.php?page=forum&op=browse&s=11&thread=2547
See a couple discussions in http://forums.no-intro.org too.
