### ISSUE TITLE
Remove GoodTools?

### ISSUE THREAD

**Issue by RobLoach** [libretro/libretro-database#757]
It's a lot of old stuff.

**Comment by kivutar** [comment]
I think that goodtools in the database causes some problems.

At first I liked it because I hoped it would allow to scan some of my hacks and fan translations.

But I find that it adds some duplicate fields, with some titles that are not as clean as no-intro. And they don't display nicely in the UI.

I think that supporting goodtools is too much work. It would be OK if we would have a small team dedicated to taking care of libretro-database carefully. But we currently don't.

My opinion on this is that we should stick with no-intro until we have a test suite to track regressions in the db. Only then, we should consider adding goodtools back.
