### ISSUE TITLE
Tomb Raider missing CRCs and Sizes

### ISSUE THREAD

**Issue by RobLoach** [libretro/libretro-database#766]
```
game (
	name "Tomb Raider 1 (PC)"
	description "First Game"
	rom ( name "TITLE.PHD" size 316138 crc 4139c54c md5 12768de79512ec9a2e4c49014378666b sha1 46bf193a45727189ae01571b1cb9e7684f51446f )
)
```

**Comment by RobLoach** [comment]
@alfrix Do you happen tohave the sizes and crc values of these entries? Thanks!

**Comment by alfrix** [comment]
actually i was about to change them to only size because that is how the core identifies them internally
look at https://github.com/XProger/OpenLara/blob/master/src/gameflow.h#L291

In case you are wondering, loading the title should be like starting the original game exe with videos and all, but currently it starts black due to a bug (https://github.com/libretro/OpenLara/issues/9)
