### ISSUE TITLE
New Nintendo Game Boy Cheats

### ISSUE THREAD

**Issue by summonthethunder** [libretro/libretro-database#991]
New Nintendo Game Boy cheats ready to be merged.  All updated from gamehacking.org and have been tested on Gambatte, mGBA, and VBA-M with no known issues on my end.

[Nintendo - Game Boy - New Cheats.zip](https://github.com/libretro/libretro-database/files/4175028/Nintendo.-.Game.Boy.-.New.Cheats.zip)

**Comment by bphd** [comment]
> New Nintendo Game Boy cheats ready to be merged. All updated from gamehacking.org and have been tested on Gambatte, mGBA, and VBA-M with no known issues on my end.
> 
> [Nintendo - Game Boy - New Cheats.zip](https://github.com/libretro/libretro-database/files/4175028/Nintendo.-.Game.Boy.-.New.Cheats.zip)

Can't manage to make work `Pocket Monsters Midori (J) (V1.0) [S][T+Eng0.03_LandaR].cht` on anything other than GearBoy (who coincidentally is the only one who claims to support cheats in its ReadMe). Is there something I'm doing wrong? Otherwise no other `Pokémon`/`Pocket Monster` `.cht` file does work at all in my situation (Pocket Monsters Midori (J) (V1.0) [S][T+Eng0.03_LandaR] ROM and all GB cores)
